# Generated by Django 4.0.3 on 2022-04-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='message',
            field=models.TextField(max_length=500),
        ),
    ]
