# Generated by Django 4.0.3 on 2022-04-20 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_alter_contactme_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='sent_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 19, 21, 9, 15, 139213)),
        ),
    ]
