# Generated by Django 4.0.3 on 2022-04-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0005_alter_contactme_sent_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
